name: Super-Linter

on: pull

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@setup-node@v2

     - name: Run Super-Linter
       uses: github/super-linter@v3
       env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
